---
- name: Déploiement Docker sur Debian
  hosts: debian
  sudo: yes
  tasks:
 
  - name: Mise à jour APT
    apt:
     update_cache: yes

  - name: Installation des composants pour Docker
    apt: name={{item}} state=installed
    with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
